### ISSUE TITLE
carregar todas as disciplinas do curso no sistema

### ISSUE THREAD

**Issue by viniciusbds** [viniciusbds/projeto-PLP#5]

**Comment by Wesley-M** [comment]
Implementei essa parte só pegando o que já tinha feito e usando um mapa para disciplinas, viu Mariana? Fique a vontade para editar se precisar.

**Comment by marianasn** [comment]
Certo! desculpa a demora pra implementar, tô tiltada com as provas kkkk muito obrigadaaa
